version: '3.3'

services:
  npm:
    image: library/node:latest
    volumes:
    - ./:/src
    working_dir: /src
    command: npm install

  ci:
    image: php:7.3-cli
    volumes:
    - ./:/src
    working_dir: /src

  composer:
    image: composer:latest
    volumes:
    - ./:/src
    working_dir: /src
    command: composer install

