services:
  npm:
    image: node:16
    volumes:
    - ./:/src
    working_dir: /src
    command: npm install

  ci:
    image: php:7.3-cli
    volumes:
    - ./:/src
    working_dir: /src

  web: 
    image: php:7.3-cli
    volumes:
    - ./:/src
    working_dir: /src
    command: make dev
    ports:
      - 80:8000

  composer:
    image: composer:1.8.6
    volumes:
    - ./:/src
    working_dir: /src
    command: composer install

