#!/usr/bin/env php
<?php declare(strict_types = 1);

require __DIR__ . '/../vendor/autoload.php';

$fileAuth = __DIR__ . '/../data/auth.json';
if ( ! file_exists(__DIR__ . '/../data/auth.json')) {
	file_put_contents(__DIR__ . '/../data/auth.json', getenv('GOOGLE_AUTH'));
}

$application = new \Contributte\Console\Application();

$application->add(
	new ActionsGenerator(
		GoogleClient::build(__DIR__ . '/../data/auth.json'),
		__DIR__ . '/../data'
	)
);

$application->add(new RepertoireGenerator(__DIR__ . '/../data'));

$application->run();
