name: Github pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: jwsi/secret-parser@v1
        with:
          filename: data/auth.json
          secret-name: private_key
          secret-value: ${{ secrets.private_key }}

      - uses: shivammathur/setup-php@v2
        env:
          GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
        with:
          php-version: 7.3
          coverage: none # default is xdebug

      - run: make init-php
      - run: make build-web

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: make init-node

      - name: Build
        run: make build-assets

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
