name: Github pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jwsi/secret-parser@v1
        with:
          filename: data/auth.json
          secret-name: private_key
          secret-value: ${{ secrets.private_key }}

      - uses: shivammathur/setup-php@v2
        env:
          GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
        with:
          php-version: 7.3
          coverage: none # default is xdebug

      - run: make init
      - run: make build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
